import { Router, Request, Response } from 'express'
import { PrismaClient } from '@prisma/client'
import { authenticateToken, checkAdmin, AuthRequest } from '../middleware/auth'
import logger from '../utils/logger'
import fs from 'fs'
import path from 'path'
import { Client, QueryResult } from 'pg'
import { Readable } from 'stream'

const router = Router()
const prisma = new PrismaClient()

// 所有数据库备份路由都需要管理员权限
router.use(authenticateToken)
router.use(checkAdmin)

// 备份目录（放在 src 下，方便 Docker volume 挂载）
const BACKUP_DIR = path.resolve(process.env.BACKUP_DIR || path.join(__dirname, '../../src/backups'))

// 确保备份目录存在
if (!fs.existsSync(BACKUP_DIR)) {
  fs.mkdirSync(BACKUP_DIR, { recursive: true })
}

// 解析数据库连接信息
const getDbConfig = () => {
  const dbUrl = process.env.DATABASE_URL
  if (!dbUrl) {
    throw new Error('DATABASE_URL 未配置')
  }
  return { connectionString: dbUrl }
}
// 生成备份文件名
const generateBackupFileName = (): string => {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5)
  return `backup_${timestamp}.sql`
}

// 导出单个表的 SQL
const exportTableSQL = async (client: Client, schema: string, tableName: string): Promise<string> => {
  const fullTableName = `"${schema}"."${tableName}"`
  
  // 获取表结构
  const columnsResult = await client.query(`
    SELECT column_name, data_type, is_nullable, column_default
    FROM information_schema.columns
    WHERE table_schema = $1 AND table_name = $2
    ORDER BY ordinal_position
  `, [schema, tableName])
  
  let sql = `-- Table: ${fullTableName}\n`
  sql += `DROP TABLE IF EXISTS ${fullTableName} CASCADE;\n`
  sql += `CREATE TABLE ${fullTableName} (\n`
  
  const columns = columnsResult.rows.map((col: any) => {
    let colDef = `  "${col.column_name}" ${col.data_type}`
    if (col.is_nullable === 'NO') colDef += ' NOT NULL'
    if (col.column_default) colDef += ` DEFAULT ${col.column_default}`
    return colDef
  })
  
  // 获取主键
  const pkResult = await client.query(`
    SELECT kcu.column_name
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
      ON tc.constraint_name = kcu.constraint_name
    WHERE tc.table_schema = $1 AND tc.table_name = $2 AND tc.constraint_type = 'PRIMARY KEY'
  `, [schema, tableName])
  
  if (pkResult.rows.length > 0) {
    const pkCols = pkResult.rows.map((r: any) => `"${r.column_name}"`).join(', ')
    columns.push(`  PRIMARY KEY (${pkCols})`)
  }
  
  sql += columns.join(',\n')
  sql += '\n);\n\n'
  
  // 导出数据
  const dataResult = await client.query(`SELECT * FROM ${fullTableName}`)
  if (dataResult.rows.length > 0) {
    for (const row of dataResult.rows) {
      const values = Object.values(row).map(v => {
        if (v === null) return 'NULL'
        if (typeof v === 'number') return v.toString()
        if (typeof v === 'boolean') return v ? 'true' : 'false'
        if (v instanceof Date) return `'${v.toISOString()}'`
        return `'${String(v).replace(/'/g, "''")}'`
      })
      sql += `INSERT INTO ${fullTableName} (${Object.keys(row).map(k => `"${k}"`).join(', ')}) VALUES (${values.join(', ')});\n`
    }
    sql += '\n'
  }
  
  return sql
}

// 导出数据库
const exportDatabase = async (): Promise<{ fileName: string; filePath: string; fileSize: number }> => {
  const client = new Client(getDbConfig())
  await client.connect()
  
  const fileName = generateBackupFileName()
  const filePath = path.join(BACKUP_DIR, fileName)
  
  let sql = ''
  sql += `-- Database backup: ${new Date().toISOString()}\n`
  sql += `-- Generated by CRM Backup System\n\n`
  
  // 获取所有用户表
  const tablesResult = await client.query(`
    SELECT table_schema, table_name
    FROM information_schema.tables
    WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
    AND table_type = 'BASE TABLE'
    ORDER BY table_schema, table_name
  `)
  
  for (const table of tablesResult.rows) {
    sql += await exportTableSQL(client, table.table_schema, table.table_name)
  }
  
  await client.end()
  
  fs.writeFileSync(filePath, sql, 'utf-8')
  const stats = fs.statSync(filePath)
  
  return { fileName, filePath, fileSize: stats.size }
}

// 恢复数据库
const restoreDatabase = async (filePath: string): Promise<void> => {
  const sql = fs.readFileSync(filePath, 'utf-8')
  
  const client = new Client(getDbConfig())
  await client.connect()
  
  // 按分号分割 SQL 语句，逐条执行
  const statements = sql
    .split(/;\n/)
    .map(s => s.trim())
    .filter(s => s && !s.startsWith('--'))
  
  for (const stmt of statements) {
    if (stmt.trim()) {
      try {
        await client.query(stmt + ';')
      } catch (error: any) {
        // 忽略一些可以容忍的错误（如表不存在）
        if (!error.message.includes('does not exist') && !error.message.includes('already exists')) {
          logger.warn('SQL 执行警告:', error.message)
        }
      }
    }
  }
  
  await client.end()
}

// 备份锁（防止并发）
let isBackingUp = false

// 获取备份记录列表
router.get('/backups', async (req: Request, res: Response) => {
  try {
    const backups = await prisma.databaseBackup.findMany({
      orderBy: { createdAt: 'desc' }
    })
    res.json(backups)
  } catch (error) {
    logger.error('获取备份记录失败:', error)
    res.status(500).json({ error: '获取备份记录失败' })
  }
})

// 创建备份（手动触发）
router.post('/backup', async (req: AuthRequest, res: Response) => {
  if (isBackingUp) {
    return res.status(409).json({ error: '备份正在进行中，请稍后再试' })
  }
  
  isBackingUp = true
  const remark = req.body.remark || '手动备份'
  
  try {
    logger.info(`开始数据库备份，操作人: ${req.user?.username || 'unknown'}`)
    
    const { fileName, filePath, fileSize } = await exportDatabase()
    
    const backup = await prisma.databaseBackup.create({
      data: {
        fileName,
        filePath,
        fileSize,
        remark,
        status: 'SUCCESS'
      }
    })
    
    logger.info(`数据库备份成功: ${fileName}, 大小: ${fileSize} bytes`)
    
    res.json({
      message: '备份创建成功',
      backup
    })
  } catch (error) {
    logger.error('创建备份失败:', error)
    
    // 记录失败
    try {
      await prisma.databaseBackup.create({
        data: {
          fileName: `backup_failed_${Date.now()}.sql`,
          filePath: '',
          fileSize: 0,
          remark: remark + '（失败）',
          status: 'FAILED',
          errorMessage: error instanceof Error ? error.message : String(error)
        }
      })
    } catch (dbError) {
      logger.error('记录备份失败信息失败:', dbError)
    }
    
    res.status(500).json({ 
      error: '创建备份失败', 
      message: error instanceof Error ? error.message : String(error)
    })
  } finally {
    isBackingUp = false
  }
})

// 下载备份文件
router.get('/backups/:id/download', async (req: Request, res: Response) => {
  try {
    const backupId = parseInt(req.params.id as string)
    
    const backup = await prisma.databaseBackup.findUnique({
      where: { id: backupId }
    })
    
    if (!backup) {
      return res.status(404).json({ error: '备份记录不存在' })
    }
    
    if (backup.status !== 'SUCCESS') {
      return res.status(400).json({ error: '该备份文件不可用' })
    }
    
    if (!fs.existsSync(backup.filePath)) {
      return res.status(404).json({ error: '备份文件不存在' })
    }
    
    res.download(backup.filePath, backup.fileName)
  } catch (error) {
    logger.error('下载备份失败:', error)
    res.status(500).json({ error: '下载备份失败' })
  }
})

// 删除备份记录
router.delete('/backups/:id', async (req: Request, res: Response) => {
  try {
    const backupId = parseInt(req.params.id as string)
    
    const backup = await prisma.databaseBackup.findUnique({
      where: { id: backupId }
    })
    
    if (!backup) {
      return res.status(404).json({ error: '备份记录不存在' })
    }
    
    // 删除物理文件
    if (backup.filePath && fs.existsSync(backup.filePath)) {
      fs.unlinkSync(backup.filePath)
    }
    
    // 删除数据库记录
    await prisma.databaseBackup.delete({
      where: { id: backupId }
    })
    
    logger.info(`备份记录已删除: ${backup.fileName}`)
    
    res.json({ message: '备份删除成功' })
  } catch (error) {
    logger.error('删除备份失败:', error)
    res.status(500).json({ error: '删除备份失败' })
  }
})

// 恢复数据库（从备份文件）
router.post('/backups/:id/restore', async (req: AuthRequest, res: Response) => {
  if (isBackingUp) {
    return res.status(409).json({ error: '备份正在进行中，无法执行恢复' })
  }
  
  const backupId = parseInt(req.params.id as string)
  
  try {
    const backup = await prisma.databaseBackup.findUnique({
      where: { id: backupId }
    })
    
    if (!backup) {
      return res.status(404).json({ error: '备份记录不存在' })
    }
    
    if (backup.status !== 'SUCCESS') {
      return res.status(400).json({ error: '该备份文件不可用' })
    }
    
    if (!fs.existsSync(backup.filePath)) {
      return res.status(404).json({ error: '备份文件不存在' })
    }
    
    logger.warn(`开始恢复数据库: ${backup.fileName}, 操作人: ${req.user?.username || 'unknown'}`)
    
    isBackingUp = true
    await restoreDatabase(backup.filePath)
    
    logger.info('数据库恢复成功')
    
    res.json({ message: '数据库恢复成功' })
  } catch (error) {
    logger.error('恢复数据库失败:', error)
    res.status(500).json({ 
      error: '恢复数据库失败', 
      message: error instanceof Error ? error.message : String(error)
    })
  } finally {
    isBackingUp = false
  }
})

// 获取备份统计信息
router.get('/backup-stats', async (req: Request, res: Response) => {
  try {
    const stats = await prisma.databaseBackup.aggregate({
      _count: { id: true },
      _sum: { fileSize: true }
    })
    
    const lastBackup = await prisma.databaseBackup.findFirst({
      where: { status: 'SUCCESS' },
      orderBy: { createdAt: 'desc' }
    })
    
    res.json({
      totalBackups: stats._count.id,
      totalSize: stats._sum.fileSize || 0,
      lastBackupAt: lastBackup?.createdAt || null,
      lastBackupSize: lastBackup?.fileSize || 0
    })
  } catch (error) {
    logger.error('获取备份统计失败:', error)
    res.status(500).json({ error: '获取备份统计失败' })
  }
})

// 获取备份定时任务配置
router.get('/backup-schedule', async (req: Request, res: Response) => {
  try {
    const config = await prisma.systemConfig.findUnique({
      where: { key: 'backup_schedule' }
    })
    
    if (!config) {
      return res.json({
        enabled: false,
        time: '02:00:00',
        retentionDays: 30
      })
    }
    
    res.json(JSON.parse(config.value))
  } catch (error) {
    logger.error('获取备份配置失败:', error)
    res.status(500).json({ error: '获取备份配置失败' })
  }
})

// 更新备份定时任务配置
router.put('/backup-schedule', async (req: Request, res: Response) => {
  try {
    const { enabled, time, retentionDays } = req.body
    
    const config = { enabled, time, retentionDays }
    
    await prisma.systemConfig.upsert({
      where: { key: 'backup_schedule' },
      update: { value: JSON.stringify(config) },
      create: {
        key: 'backup_schedule',
        value: JSON.stringify(config)
      }
    })
    
    logger.info('备份配置已更新:', config)
    
    res.json({ message: '配置保存成功' })
  } catch (error) {
    logger.error('保存备份配置失败:', error)
    res.status(500).json({ error: '保存备份配置失败' })
  }
})

export default router
